version: '3'
services:
  mongo:
    external:
      name: mongo_instance

  app:
    build: 
      context: .
      dockerfile: dockerfile
      args:
        - PORT=${PORT}
    restart: always
    container_name: cpen321_app
    environment:
      - DB_URI=${DB_URI}
      - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mongo
    networks:
      - cpen321-tutorial_default
    command: npm start

networks:
  cpen321-tutorial_default:
    external: true
