name: CI - Run Tests

on:
    push:
      paths:
        - 'Backend/**'  # Only trigger deployment if changes occur in the Backend folder
        
      branches:
        - main
        
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: Backend/package-lock.json

      - name: Install Dependencies
        run: |
          cd Backend  # ✅ Move into the Backend folder
          npm install

      - name: Set Environment Variables
        run: |
          echo "DB_URI=${{ secrets.DB_URI_TEST }}" >> $GITHUB_ENV
          echo "PORT=${{ secrets.PORT_TEST }}" >> $GITHUB_ENV

      - name: Run Tests
        run: |
          cd Backend  # ✅ Move into the Backend folder
          npm test

      - name: Upload Jest Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: Backend/coverage/  # ✅ Ensure correct coverage pat